name: Test it

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Protoc
        uses: arduino/setup-protoc@v1            
      - run: cargo build --release

      - name: Build default
        run: cargo build

      - name: Build adjust-server-stream         
        run: cargo build --features adjust-server-stream